### ISSUE TITLE
Compiling process hanging when using mongodb crate with actix-web 3.0

### ISSUE THREAD

**Issue by maicallist** [actix/actix-web#1688] opened 2020-09-17 02:21 UTC
## Current Behavior
The application is built on top of actix-web 3.0 accessing MongoDB via 1.1.1 driver on tokio runtime.
when building the application with cargo, the building process hangs on one line of code.

```
#[post("/search_username")]
pub(crate) async fn query_user(
    mongo_conn: Data<Client>,
    form: web::Form<Username>
) -> HttpResponse {
    let username = &form.username;
    let collection = mongo_conn.database("ngiam-db").collection("userEntity");
    let filter = doc! {"username":username};
    let fo = FindOptions::builder()
        .projection(doc! {"username":1, "displayName":1, "groupChain":1,
        "_id":0}) .build();
    let cursor = collection.find(filter, fo).await;    ######### this line
 
    unimplemented!()
}

```

strace cargo build reports
![Screen Shot 2020-09-15 at 13 46 30](https://user-images.githubusercontent.com/6936908/93411180-2589e680-f8cd-11ea-8412-3d4ffbc59bd9.png)

the hanging rustc process eventually exhausts all memory.

This issue currently can be avoided by switching MongoDB driver to async-std runtime.

## Possible Solution
MongoDB driver maintainer suggests it might be one of proc macro in actix-web causing the issue.

## Steps to Reproduce (for bugs)
MCVE is available at [here](https://github.com/maicallist/rust_mongo_558)

Discussion with the MongoDB driver maintainer is available [here](https://jira.mongodb.org/projects/RUST/issues/RUST-558?filter=allopenissues)

## Your Environment

- MacOS 10.15.6
- Parallels Desktop 15
- Debian 10.5
- Rust Version rustc 1.46.0 (04488afe3 2020-08-24)
- Actix Web Version: 3.0.1, 3.0.2

**Comment by fakeshadow** [comment] 2020-09-17 04:21
Nah it most likely have nothing to do with proc macros. You can remove the macros and try it again to see if it solves the issue for you.

Similar issue has been reported and it's solved by pinning rustc to a lower version for example 1.44.0 stable.

The course of the memory leak is yet unknown to me so I wouldn't comment on the issue is cause by which or what.

**Comment by Neopallium** [comment] 2020-09-21 04:28
I have also had rust 1.46 hang while compiling.  I had to downgrade to 1.45.2.

Might be related to rust issue https://github.com/rust-lang/rust/issues/75992

**Comment by Voronar** [comment] 2020-11-19 16:52
Same problem on my machine:
- linux: 5.4.0-53-generic 18.04.1-Ubuntu
- rustc: 1.46.0 (04488afe3 2020-08-24)
- actix-web: 3.2.0
- mongodb: 1.1.1

P.S. Problem solved with update to rust 1.48

**Comment by robjtede** [comment] 2020-11-19 17:00
New readers, please try again with rustc 1.48 and/or latest nightly and report back.

Once we have a few reports of the problem being solved we can close this.

**Comment by maicallist** [comment] 2020-11-20 02:42
1.48 fixed this issue for me.

**Comment by robjtede** [comment] 2020-11-27 01:15
tentatively closing this, though the upstream issue has been re-opened

**Closed as completed by robjtede** 2020-11-27 01:15 UTC
Labels: C-bug-upstream
