### ISSUE TITLE
the trait Responder is not implemented for NamedFile

### ISSUE THREAD

**Issue by ArunGust** [actix/actix-web#2700] opened 2022-03-18 05:24 UTC
I got below error after moving from 3.x to 4.x

 .route("/{filename}", actix_web::web::get().to(files)),
    |                                                             ^^ the trait `Responder` is not implemented for `NamedFile`
    |
    = note: required because of the requirements on the impl of `Responder` for `Result<NamedFile, actix_web::Error>`
note: required by a bound in `Route::to`
   --> C:\RUST\CARGO\registry\src\github.com-1ecc6299db9ec823\actix-web-4.0.1\src\route.rs:186:20
    |
186 |         F::Output: Responder + 'static,
    |                    ^^^^^^^^^ required by this bound in `Route::to`

**Comment by aliemjay** [comment] 2022-03-18 05:28
Can be version mismatch between actix-web and actix-files. What versions dou you use?

**Comment by robjtede** [comment] 2022-03-18 11:05
duplicate of https://github.com/actix/actix-website/issues/265

**Closed as completed by robjtede** 2022-03-18 11:05 UTC
Labels: duplicate

**Comment by ArunGust** [comment] 2022-03-19 10:38
Worked. Thank you
