### ISSUE TITLE
Middleware Logger not logging errors thrown by middleware

### ISSUE THREAD

**Issue by hlb8122** [actix/actix-web#1051] opened 2019-08-23 13:07 UTC
I have a middleware to check for payments.

It has signature
```rust
impl<S> Transform<S> for CheckPayment
where
    S: Service<Request = ServiceRequest, Response = ServiceResponse<Body>, Error = Error>,
    S::Future: 'static,
{
    type Request = ServiceRequest;
    type Response = ServiceResponse<Body>;
    type Error = Error;
    type InitError = ();
    type Transform = CheckPaymentMiddleware<S>;
    type Future = FutureResult<Self::Transform, Self::InitError>;
```
```rust
pub struct CheckPayment(BitcoinClient, WalletState);

impl CheckPayment {
    pub fn new(client: BitcoinClient, wallet_state: WalletState) -> Self {
        CheckPayment(client, wallet_state)
    }
}

impl<S> Transform<S> for CheckPayment
where
    S: Service<Request = ServiceRequest, Response = ServiceResponse<Body>, Error = Error>,
    S::Future: 'static,
{
    type Request = ServiceRequest;
    type Response = ServiceResponse<Body>;
    type Error = Error;
    type InitError = ();
    type Transform = CheckPaymentMiddleware<S>;
    type Future = FutureResult<Self::Transform, Self::InitError>;
```
and have an ```ServerError``` enum which implements ```error::ResponseError```.

During the ```CheckPaymentMiddleware``` ```call``` function errors can are thrown and converted as follows:
```return Box::new(err(ServerError::Payment(PaymentError::InvalidAuth).into()))```.

The errors are picked up by actix_http
```
[2019-08-23T12:58:18Z ERROR actix_http::response] Internal Server Error: Payment(AddrFetchFailed)
```
but are not picked up by the logger (and hence aren't formatted with important information) which is instantiated as follows:
```rust
        App::new()
            .wrap(Logger::default())
            .wrap(Logger::new("%a %{User-Agent}i"))
            .service(
                // Key scope
                web::scope("/keys").service(
                    web::resource("/{addr}")
                        .data(key_db_inner)
                        .wrap(CheckPayment::new(
                            bitcoin_client_inner.clone(),
                            wallet_state_inner.clone(),
                        )) // Apply payment check to put key
                        .route(web::get().to(get_key))
                        .route(web::put().to_async(put_key)),
                ),
            )
```

Is this expected behavior? How do I pass the error through to the outer logging middleware?

**Comment by neoeinstein** [comment] 2019-08-23 13:13
Is the issue for you that the request is not generating a line from the `Logger` middleware with the 500 status, and seems to be bypassing the logger altogether?

**Comment by hlb8122** [comment] 2019-08-23 13:23
> Is the issue for you that the request is not generating a line from the `Logger` middleware with the 500 status, and seems to be bypassing the logger altogether?

Yes. The error is caught by `actix_http::response` but is bypassing the `Logger`.

**Comment by neoeinstein** [comment] 2019-08-23 13:33
The `Logger` middleware ends up generating a `Future` called `LoggerResponse`, which ends up wrapping the inner set of calls. As part of that, it has a `try_ready!`, which short-circuits the logging when the internal service returns an error:

https://github.com/actix/actix-web/blob/23d768a77b42c5df45ef76bbc1f84cfee62ee09c/src/middleware/logger.rs#L195-L210

This looks like intended behavior, but I'll let @fafhrd91 confirm. If this is an error that you expect to know and handle, instead of returning an `Error`, you could generate the appropriate `HttpResponse`: `HttpResponse::InternalServerError().body("whoops!")`. Nonetheless, it would probably be better to receive the error and still emit a log message, even if the inner service is returning an error.

Would be interested in seeing a PR proposed for how this would be better logged.

**Comment by hlb8122** [comment] 2019-08-23 13:37
@neoeinstein 
I expected this may be the work around.

> Nonetheless, it would probably be better to receive the error and still emit a log message, even if the inner service is returning an error.

It does seem a shame I have all the machinery in the `Service`trait to handle errors but I just have to return an `Ok(HttpResponse...)`.

Thanks for the `Response`, look forward to any follow ups.

**Comment by fafhrd91** [comment] 2019-08-23 16:29
@hlb8122 did you register logger as last middleware?

**Comment by hlb8122** [comment] 2019-08-24 02:47
> @hlb8122 did you register logger as last middleware?

@fafhrd91 Yep, I tried various permutations of where I register it too.

```rust
App::new()
            .wrap(Logger::default())
            .wrap(Logger::new("%a %{User-Agent}i"))
            .service(
                // Key scope
                web::scope("/keys").service(
                    web::resource("/{addr}")
                        .data(key_db_inner)
                        .wrap(CheckPayment::new(
                            bitcoin_client_inner.clone(),
                            wallet_state_inner.clone(),
                        )) // Apply payment check to put key
                        .route(web::get().to(get_key))
                        .route(web::put().to_async(put_key)),
                ),
            )
```

**Comment by fafhrd91** [comment] 2019-08-31 10:32
I re-read this ticket, I think you should just log your Error yourself. Logger middleware does not log errors, just response.

**Comment by hlb8122** [comment] 2019-09-01 02:26
@fafhrd91 Sure.

As @neoeinstein said, I'd embrace a PR which changes this behavior because errors are logged when returning error types in the following example:

```rust
#[derive(Debug)]
enum FooError {
    Bar,
}

impl fmt::Display for FooError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "display message")
    }}

impl ResponseError for FooError {
    fn error_response(&self) -> HttpResponse {
        HttpResponse::BadRequest().finish()
    }
}

fn foo_route() -> Result<String, FooError> {
    Err(FooError::Bar)
}

pub fn main() {
    use actix_web::{App, HttpServer};

    std::env::set_var("RUST_LOG", "actix_web=info");
    env_logger::init();

    HttpServer::new(|| {
        App::new()
            .wrap(Logger::default())
            .wrap(Logger::new("%a %{User-Agent}i"))
            .route("/error", web::get().to(foo_route))
    })
    .bind("127.0.0.1:8088")
    .unwrap()
    .run()
    .unwrap();
}
```

```
[2019-09-01T02:24:36Z INFO  actix_web::middleware::logger] 127.0.0.1:54184 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
[2019-09-01T02:24:36Z INFO  actix_web::middleware::logger] 127.0.0.1:54184 "GET /error HTTP/1.1" 400 15 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0" 0.002036
```

**Comment by fafhrd91** [comment] 2019-09-01 06:57
Closing, as I don’t think logger middleware should log errors

**Closed as completed by fafhrd91** 2019-09-01 06:57 UTC

**Comment by hlb8122** [comment] 2019-09-02 04:20
@fafhrd91 
You've missed the point. Error response generated by an error returned by middleware are not logged, whereas error responses generated by a services handler returning an error are. 

Look at the example I just wrote for you. 

This should remain open.

**Comment by fafhrd91** [comment] 2019-09-02 05:34
I see, but logger middleware work with responses only, it does not do anything with errors. Errors are not handled by middlewares.

**Comment by hlb8122** [comment] 2019-09-02 08:38
@fafhrd91 
The error response which my middleware generates (when a Err(ServerError::..) is returned) is a response.

In both the service and middleware examples the function signature is nearly identical, both have codomain `Result<Value, ErrorType>` where `ErrorType` implements `ResponseError`.

After an `Err` is returned the service's route function `Response` gets logged, whereas the middlewares `Response` doesn't.

**Comment by fafhrd91** [comment] 2019-09-02 09:58
Err() is not a response. Return Ok() and it will be logged

**Comment by fafhrd91** [comment] 2019-09-02 10:05
This is not a bug, this is expected behavior.

**Comment by hlb8122** [comment] 2019-09-02 10:32
> Err() is not a response. Return Ok() and it will be logged

I know this and I never said it was.

You still don't understand what I'm saying. When the middleware returns an error the client receives a response. The response is given by the Err(..) generated by the `ErrorResponse` trait. 

**This response is not logged.** 

This is clearly an issue worth looking into I have no idea why your dismissing it. Imagine someone setting up the framework, using the `Logger` and not failing to have any many of their responses logged when they are created by the middleware throwing an error. It's not documented anywhere that this would be the case and could cause serious problems in production settings.

**Comment by hlb8122** [comment] 2019-09-02 11:19
You still don't get what I mean. Rather than get frustrated I've written you a minimal demonstration of the problem:

```rust
use actix_web::{HttpServer, web, App, HttpResponse, error::ResponseError, Error, middleware::Logger};
use actix_web::{dev::ServiceRequest, dev::ServiceResponse};
use std::fmt;
use futures::future::{ok, FutureResult};
use futures::{Future, Poll};
use actix_service::{Service, Transform};

#[derive(Debug)]
enum FooError {
    Bar,
}

impl fmt::Display for FooError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "display message")
    }
}

impl ResponseError for FooError {
    fn error_response(&self) -> HttpResponse {
        HttpResponse::BadRequest().finish()
    }
}

fn foo_route() -> Result<String, FooError> {
    Ok("hello".to_string())
}

pub fn main() {

    std::env::set_var("RUST_LOG", "actix_web=info");
    env_logger::init();

    HttpServer::new(|| {
        App::new()
            .wrap(Logger::default())
            .wrap(Logger::new("%a %{User-Agent}i"))
            .wrap(SayHi)
            .route("/hello", web::get().to(foo_route))
    })
    .bind("0.0.0.0:8088")
    .unwrap()
    .run()
    .unwrap();
}

pub struct SayHi;

// Middleware factory is `Transform` trait from actix-service crate
// `S` - type of the next service
// `B` - type of response's body
impl<S, B> Transform<S> for SayHi
where
    S: Service<Request = ServiceRequest, Response = ServiceResponse<B>, Error = Error>,
    S::Future: 'static,
    B: 'static,
{
    type Request = ServiceRequest;
    type Response = ServiceResponse<B>;
    type Error = Error;
    type InitError = ();
    type Transform = SayHiMiddleware<S>;
    type Future = FutureResult<Self::Transform, Self::InitError>;

    fn new_transform(&self, service: S) -> Self::Future {
        ok(SayHiMiddleware { service })
    }
}

pub struct SayHiMiddleware<S> {
    service: S,
}

impl<S, B> Service for SayHiMiddleware<S>
where
    S: Service<Request = ServiceRequest, Response = ServiceResponse<B>, Error = Error>,
    S::Future: 'static,
    B: 'static,
{
    type Request = ServiceRequest;
    type Response = ServiceResponse<B>;
    type Error = Error;
    type Future = Box<dyn Future<Item = Self::Response, Error = Self::Error>>;

    fn poll_ready(&mut self) -> Poll<(), Self::Error> {
        self.service.poll_ready()
    }

    fn call(&mut self, req: ServiceRequest) -> Self::Future {
        Box::new(futures::future::err(FooError::Bar.into()))
    }
}
```

The app sends the response "display message"  to the client. **This is not logged though.**

**Comment by fafhrd91** [comment] 2019-09-02 14:32
I understand and I repeate, this is explicit decision for middlewares pipeline. Middlewares do not handle errors, especially logger middleware. Return Response and you’ll see you Error.

**Comment by hlb8122** [comment] 2019-09-03 01:19
> Middlewares do not handle errors, especially logger middleware.

Unless they are ejected out of handlers...as shown in the example from two days ago.

```rust
fn foo_route() -> Result<String, FooError> {
    Err(FooError::Bar)
}
```

If you're going to take this bizarre and contradictory design decision it should be documented somewhere.

**Comment by jrconlin** [comment] 2020-04-21 19:29
Can we consider reopening this issue?

Middleware is how every request and response is handled. To eat Errors and only allow response bodies can lead to some fairly atrocious hacks, particularly when dealing with reporting systems like Sentry. I have to be super mindful when I log an error inside of any middleware processor to include it in the response data state and then have my sentry reporting middleware check for that state entry, and even that won't capture every event because there could be some that slip by. 

If there's a better pattern for this, I'm happy to implement one.

**Comment by detailyang** [comment] 2020-08-27 06:40
workarounds: return Ok<T> instead Err<T>.

**Comment by blkt** [comment] 2021-02-16 11:30
+1

https://httpd.apache.org/docs/2.4/logs.html#accesslog
https://docs.nginx.com/nginx/admin-guide/monitoring/logging/#setting-up-the-access-log

> The server access log records all requests processed by the server.

Can we consider reopening the issue?

**Comment by mcronce** [comment] 2022-07-29 05:07
+1 on reopening.  Not getting a response logged when it happened to originate from an Err condition in middleware is unexpected behavior at best.

**Comment by bvrooman** [comment] 2023-04-29 03:17
I would also like to see this issue reopened as I find this behaviour to be unintuitive and unergonomic. I am experiencing a problem similar to that of the author of this issue. I have a middleware that can succeed or fail - I read the `Authentication` header from the request and parse the value and validate it. On a successful parse/validation, I modify the request extensions; on fail, I respond with an error message. However, such requests where the failure occurs are never logged, as if they never happened.
 
Currently, the alternative is not to use middleware, and to do this verification step at each endpoint. This defeats the purpose of middleware, and creates a high maintenance toll. Logging requests where the response is generated by the middleware would be very helpful.
