### ISSUE TITLE
Async/Await and futures 0.3

### ISSUE THREAD

**Issue by xacrimon** [actix/actix-web#975] opened 2019-07-14 20:35 UTC
Now that the async story is cleaned up and async await is set for release in Rust 1.38 it may be time to investigate switching to futures 0.3. It doesnt seem to be extremely complicated work actually. Mostly changing syntax and typedefs. Sticking to futures 0.1 is not a viable option as the whole ecosystem will transform to 0.3. Tokio and Hyper are already well ahead in this regard, with 0.3 development on master.

**Comment by pythoneer** [comment] 2019-07-14 22:07
is this a duplicate of #955 ?

**Comment by xacrimon** [comment] 2019-07-14 22:12
Seems like it.

**Comment by fafhrd91** [comment] 2019-07-16 04:18
dup of #955

**Closed as completed** 2019-07-16 04:18 UTC
