### ISSUE TITLE
When cross compile to Linux : thread 'main' panicked at 'OpenSSL include directory does not exist: /usr/lib64/openssl/include'

### ISSUE THREAD

**Issue by chenyangguang** [actix/actix-web#2985] opened 2023-02-26 08:04 UTC
Your issue may already be reported! Please search on the [Actix Web issue tracker](https://github.com/actix/actix-web/issues) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

- Rust Version (I.e, output of `rustc -V`):
- Actix Web Version:

**Comment by robjtede** [comment] 2023-02-26 13:02
Dupe of #2986

**Closed as completed** 2023-02-26 13:02 UTC
Labels: duplicate
