### ISSUE TITLE
Doc - server is not public module

### ISSUE THREAD

**Issue by l-7-l** [actix/actix-web#939] opened 2019-06-24 17:16 UTC
[documentaion hello world](https://actix.rs/docs/getting-started/)

## Description
i follow this:
```rust
extern crate actix_web;
use actix_web::{server, App, HttpRequest};

fn index(_req: &HttpRequest) -> &'static str {
    "Hello world!"
}
```
## Unexpected

* server is private module
* the router handler's parameters and return have changed
* > what is info.0 info.1 ?
    can i use `info.name` and `info.id` Or `let (name, id) = info` ?
<img width="1119" alt="Screen Shot 2019-06-25 at 1 19 21 AM" src="https://user-images.githubusercontent.com/20581031/60038574-52117b80-96e7-11e9-964b-e659b1489b1c.png">

## Meta
```
[dependencies]
actix-web = "1.0.2"

```

**Comment by roman-holovin** [comment] 2019-06-24 20:28
Tutorial is for version 0.7, while you are using version 1.0.2. AFAIK, documentation hasn't been updated  to the latest version yet.

There are plenty of updated examples which you can follow in this [repo](https://github.com/actix/examples)

**Comment by cldershem** [comment] 2019-06-24 21:51
This is a duplicate of #901 and #722. For more up-to-date docs, please use the [examples](http://github.com/actix/examples) repo, the [api docs](https://docs.rs/actix-web/), and the [PR to update the docs](https://github.com/actix/actix-website/pull/90).

**Closed as completed by cldershem** 2019-06-24 21:51 UTC
