### ISSUE TITLE
Allow access to the request when rendering errors

### ISSUE THREAD

**Issue by chanks** [actix/actix-web#1159] opened 2019-11-09 13:16 UTC
I have a custom error type that implements ResponseError:

```rust
impl actix_web::error::ResponseError for PlatformError {
    fn error_response(&self) -> HttpResponse {
        // implementation
    }
}
```

The problem is that I have no access to the http request for context, so I can't determine:
- Whether to render the error as JSON or HTML
- What language the error should be translated into
- The uuid of the request (which I injected in a middleware) for logging purposes

**Comment by danielparks** [comment] 2019-11-28 06:36
Being able to access the registered data would be useful too.

**Comment by danielparks** [comment] 2019-11-28 06:43
Actually, it looks like this is a dupe of #242 — Should `ResponseError::error_response` accept `req`?

**Comment by fafhrd91** [comment] 2019-11-28 15:15
I’ll try to address this before 2.0 release

**Comment by chanks** [comment] 2019-11-28 17:48
Thank you @fafhrd91 - it'd be a breaking change in the API, so that makes sense.

**Comment by fafhrd91** [comment] 2019-12-16 15:49
unfortunately, this change requires too much work. postpone this to next major release. 

closing in favor of original #242

**Closed as completed by fafhrd91** 2019-12-16 15:49 UTC
