### ISSUE TITLE
Cannot get application/x-www-form-urlencoded payload parsed with web::Form extractor

### ISSUE THREAD

**Issue by Pzixel** [actix/actix-web#2044] opened 2021-03-05 10:45 UTC
## Expected Behavior
application/x-www-form-urlencoded data get parsed correctly

## Current Behavior
It doesn't

## Possible Solution
Move from `serde_urlencoded` to `serde_qs` as default form parser

## Steps to Reproduce (for bugs)
Consider following form that want to post data to actix webserver:

```html
    <select name="id_cat" multiple id="">
        <option value="1"> Cat1   </option>
        <option value="2"> Cat2   </option>
        <option value="3"> Cat3   </option>
        <option value="9"> Cat9  </option>
    </select>
 ```
 
 It produces a request like `curl --location --request POST '127.0.0.1:8080/' --data-raw 'text=hello&id_cat[]=2&id_cat[]=9'`

Let's not try parsing it using two libraries:

```rust
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Payload {
    pub text: String,
    pub id_cat: Vec<String>
}

fn main() {
    let str = "text=hello&id_cat[]=2&id_cat[]=9";
    let x1 = serde_urlencoded::from_str::<Payload>(str);
    println!("{:?}", x1);
    let x2 = serde_qs::from_str::<Payload>(str);
    println!("{:?}", x2);
}
```

You can see that `serde_urlencoded` fails to parse some very simple inputs which renders current default `web::Form` extractor unusable for virtually any real-world use case, e.g. any form multiselect dropdown won't be able to get posted back to the server.

**Comment by robjtede** [comment] 2021-03-05 10:49
duplicate of #1815

**Closed as completed by robjtede** 2021-03-05 10:49 UTC
Labels: duplicate

**Comment by Pzixel** [comment] 2021-03-05 10:50
Why is it duplicate? It has nothing to do with numbers, you can use strings if you want.

The problem is `serde_urlencoded` just not able to process some scenarios that are *required* for a real world apps

**Comment by robjtede** [comment] 2021-03-05 10:50
serde_qs already has partial actix support, maybe you could submit a PR to it for a variation on the Form extractor: https://docs.rs/serde_qs/0.8.2/serde_qs/actix/index.html

**Comment by robjtede** [comment] 2021-03-05 10:51
> Why is it duplicate?

it is duplicate because any fix for 1815 would fix this

**Comment by Pzixel** [comment] 2021-03-05 10:54
I can see #1816 but I fail to see why it didn't get merged. Can you give any insights on the matter? 

Of course I can make a PR to `serde_qs` but it looks like using `serde_urlencoded` as default may be suboptimal

**Comment by robjtede** [comment] 2021-03-05 10:55
from #1815

> The problem here is that serde_qs is not behaving in a spec compliant way here.

**Comment by robjtede** [comment] 2021-03-05 10:58
> looks like using serde_urlencoded as default may be suboptimal

Spec compliance by default is a choice of this project.
You are free to create your own extractor that behaves as you wish in only a few lines of code.

**Comment by Pzixel** [comment] 2021-03-05 11:04
Hmm, that's weird, I always thought that arrays are spec'd as well.

Okay, apparently I was wrong. Thanks for your time
