### ISSUE TITLE
actix-web-actors  WS  BaseHttpResponseBuilder vs  HttpResponseBuilder

### ISSUE THREAD

**Issue by mvniekerk** [actix/actix-web#2195] opened 2021-05-02 13:46 UTC
## Expected Behavior
actix-web-actors v4.0.0-beta.4 from cargo compiles
## Current Behavior
It doesn't compile because pub use HttpResponseBuilder was renamed to  BaseHttpResponseBuilder. Thus ws.rs points to the ether.

## Steps to Reproduce (for bugs)
1. Add  actix-web = { version = '4.0.0-beta.6', features = ["openssl"] } to Cargo.toml
2. Add actix-web-actors = { version = "4.0.0-beta.4" } to Cargo.toml 
3. Hit compile

## Context
Tried to make a websocket web actor

## Your Environment
* Rust Version (I.e, output of `rustc -V`): 1.51
* Actix Web Version: v4 b6

**Comment by purkhusid** [comment] 2021-05-04 11:28
Yeah, I think actix-web-actors needs a new release.

**Comment by gbaranski** [comment] 2021-05-05 17:35
Same issue, I've added this to Cargo.toml and it worked
```toml
actix-web-actors = { git = "https://github.com/actix/actix-web" }
```

**Comment by mvniekerk** [comment] 2021-05-07 08:21
Who does releases on actix? Who needs to be cc-ed into this?

**Comment by xaocon** [comment] 2021-06-15 16:51
> Who does releases on actix? Who needs to be cc-ed into this?

robjtede does most of the development and releases but keep in mind that the problem is fixed in code and the problem exists in beta. Just pull from git if you're helping test beta.

**Comment by robjtede** [comment] 2021-06-19 11:30
beta.7 is released

**Closed as completed** 2021-06-19 11:30 UTC
