### ISSUE TITLE
Can't curl an HttpResponse

### ISSUE THREAD

**Issue by robert-snakard** [actix/actix-web#1213] opened 2019-12-13 16:29 UTC
Hey Actix community, I'm running into a bug with the basic Actix tutorial. I've got the most basic HttpServer
```
fn index() -> impl Responder {
    println!("logging request at index");
    HttpResponse::Ok().body("Hello World");
}

fn main() {
    HttpServer::new(|| {
        App::new()
            .route("/", web::get().to(index))
    })
    .bind("127.0.0.1:8088")
    .unwrap()
    .run()
    .unwrap();
}
```

When I curl the webpage `curl --request GET --url http://localhost:8088` the println will print but curl will not output Hello World. Why is the response empty?

**Comment by HiruNya** [comment] 2019-12-14 08:54
The semicolon on the third line (where you return the HttpResponse) causes the function to return ``()`` instead of an ``HttpResponse`` struct. Since ``()`` implements ``Responder``, the compiler doesn't raise an error. However the ``()`` returns a Status 200, with no body.

You can see this if you change the ``impl Responder`` to an `HttpResponse` as now the compiler can see that the types don't match up.

If you remove the semicolon on that line, it should work as intended. (Or you can put a ``return`` statement there.)

This Issue is related to #1108 and seems to be fixed in v2.0.

**Closed as completed** 2019-12-14 17:12 UTC
