### ISSUE TITLE
actix-http: Compilation fails

### ISSUE THREAD

**Issue by crone123** [actix/actix-web#3298] opened 2024-02-26 12:48 UTC
Hello,
The compilation of actix-http fails on latest rust version (macos, intel):
```
error[E0277]: cannot subtract `TimeDelta` from `Tm`
   --> /Users/valentin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-http-1.0.1/src/cookie/jar.rs:224:44
    |
224 |             cookie.set_expires(time::now() - Duration::days(365));
    |                                            ^ no implementation for `Tm - TimeDelta`
    |
    = help: the trait `Sub<TimeDelta>` is not implemented for `Tm`
    = help: the following other types implement trait `Sub<Rhs>`:
              <Tm as Sub<time::Duration>>
              <Tm as Sub>

error[E0308]: mismatched types
   --> /Users/valentin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-http-1.0.1/src/cookie/mod.rs:736:40
    |
736 |         self.set_expires(time::now() + twenty_years);
    |                                        ^^^^^^^^^^^^ expected `Duration`, found `TimeDelta`

```

Actix web verison: 2.0.0
Actix http version: 1.0.1

Tested versions:
Rust: rustc 1.70.0 (90c541806 2023-05-31)
Rust: rustc 1.76.0 (07dca489a 2024-02-04)
Rust: rustc 1.78.0-nightly (381d69953 2024-02-24)

Environnement:
MacOS: 13.6.4 (22G513), Intel

Thanks for checking 🙏

**Comment by robjtede** [comment] 2024-02-26 14:06
duplicate of #3135

see https://github.com/actix/actix-web/issues/3135#issuecomment-1718491296

**Closed as not planned by robjtede** 2024-02-26 14:06 UTC
Labels: duplicate
