### ISSUE TITLE
Can URLs support multiple? The same link supports multiple settings

### ISSUE THREAD

**Issue by sunkaifei** [actix/actix-web#3434] opened 2024-07-18 12:09 UTC
Can URLs support multiple? The same link supports multiple settings, such as arrays in Java Spring, for example: 

`@GetMapping(value = {"/a-{area}/" , "/a-{area}-{p}/"})`

**Comment by robjtede** [comment] 2024-07-18 12:24
duplicate of #3433

**Closed as not planned by robjtede** 2024-07-18 12:24 UTC
Labels: duplicate
