### ISSUE TITLE
Can you pub 'AppEntry' for reduce repetitive code?

### ISSUE THREAD

**Issue by XyLyXyRR** [actix/actix-web#2073] opened 2021-03-14 14:24 UTC
Hi, there. I'm adding test system to my project. But I have a little problem now.

```rust
#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| App::new().service(index))
        .run()
        .await
}

#[cfg(test)]
mod tests {
    use super::*;
    use actix_web::{rt as actix_rt, test};

    #[actix_rt::test]
    async fn _server() {
        let mut app = test::init_service(App::new().service(index));
    }
```

This code wrote two times `App::new()`, I tried to put it into function like this:
```rust
use actix_web::body::Body;

fn init() -> App<AppEntry, Body> {
    App::new().service(index)
}
```

But `AppEntry` is private, so can you pub this struct or something?

**Comment by robjtede** [comment] 2021-03-14 14:27
The recommended solution is `App::configure`.

**Comment by robjtede** [comment] 2021-03-14 14:28
Duplicate of https://github.com/actix/actix-web/issues/2039.

**Closed as completed by robjtede** 2021-03-14 14:27 UTC
Labels: duplicate
