### ISSUE TITLE
Client timeout with long URL

### ISSUE THREAD

**Issue by mlodato517** [actix/actix-web#1885] opened 2021-01-07 22:37 UTC
If I make a request to an `actix-web` server where the URL is > 32K-ish characters then I get a client timeout after 5s.

## Steps to Reproduce 
1. Clone https://github.com/actix/examples
2. `cargo run --release --bin hello-world`
3. curl -v "http://localhost:8000?foo=bar&foo=bar&foo=bar..." at least 32710 characters long
4. Observe a 408 after 5s

* Rust Version: 1.48.0

Note that I see the 408 when the URL is 32,713 characters long but not when it's 32,704 characters long. Not sure if the url + headers is exceeding 32KB and causing an issue.

[Original Gitter Comment](https://gitter.im/actix/actix-web?at=5ff77665e578cf1e95d3ecac)

**Comment by robjtede** [comment] 2021-01-08 02:02
Dispatcher gets stuck trying to parse the request head but can't because it's over the high-water buffer size (of, you guessed it, 32kB) in h1/dispatcher. Looking into supporting up to 100kB requests if it can be done without hurting perf or mem usage in normal cases.

Either way, this sort of request head too large case should be met with a 400 error or even better, a [HTTP 431 error](https://tools.ietf.org/html/rfc6585#section-5).

**Comment by mlodato517** [comment] 2021-01-08 13:44
Interesting! Thanks for looking into this. Maybe a silly question but, if we expect most requests to be small, then does allowing reading more cause issues in the normal case? Could the buffer be allocated with the same initial capacity so that most apps don’t use more memory but we allow reading more than that if need be (or if user specified or something to avoid HUGE requests DoSing things)?

**Comment by fakeshadow** [comment] 2021-01-27 03:44
https://github.com/actix/actix-web/pull/1929

This PR would restores support for 128k head.

This issue is caused by the bug introduced by https://github.com/actix/actix-web/pull/1550.
It wrongly place a hard return on read buffer exceed HW_BUFFER_SIZE when the actual decoder::MAX_BUFFER_SIZE is 128kb. So any buffer larger than 32kb would end up in a loop until timed out as 408.

The correct behavior should either change MAX_BUFFER_SIZE to 32kb so PraseError::TooLarge can return and give client a clear understanding the nature of error.
Or what I prefer only early return when 128kb max buffer size is hit and convert it to an error to client. HW_BUFFER_SIZE is meant for a growable buffer so we don't hit max buffer size right away. It's not meant for the actual max buffer.

From my tests actix-web 2.0 behaves correctly on large head. (The git rev has problem compile on 3.0 alphas so I can't test the exact rev before the change)

**Comment by fakeshadow** [comment] 2021-02-07 12:50
This is fixed by the master branch. The limit of request head is now above 128kb. Payload over shoot may return as 413 error.

**Closed as completed by fakeshadow** 2021-02-07 12:50 UTC
Labels: A-http

**Comment by mlodato517** [comment] 2021-02-07 14:29
Thanks for addressing this! And, just to check, if my application needed to handle URLs larger than 128kb, would the correct approach be to fork the repo and increase the `MAX_BUFFER_SIZE` you mention?

**Comment by fakeshadow** [comment] 2021-02-07 14:59
> Thanks for addressing this! And, just to check, if my application needed to handle URLs larger than 128kb, would the correct approach be to fork the repo and increase the `MAX_BUFFER_SIZE` you mention?

Yes and this is the size you want to modify https://github.com/actix/actix-web/blob/deafb7c8b8038b3ab4bb80cf9b465a30453c7d44/actix-http/src/h1/decoder.rs#L17.

There are something to take note though:
The limit is not hard as there is no extra check on the exact buffer size so you may find over shoot the limit by a bit would work sometimes and fail in others.(some tricky sized buffer could slipt through the limit and do one more read.)

It's possible to make this size configurable and you can start an issue for asking this feature or even better make a PR if you interested in implementing this.
