### ISSUE TITLE
Outdated guide

### ISSUE THREAD

**Issue by nikandlv** [actix/actix-web#1239] opened 2019-12-27 16:28 UTC
Hey, actix is great but the docs and https://actix.rs/ is not updated. this makes it hard for starters to get started with actix.
any eta for the doc update?

**Comment by JohnTitor** [comment] 2019-12-27 16:33
We consider updating the website but don't have an eta for now. Of course, PR is welcome!

Closing as duplicate of https://github.com/actix/actix-website/issues/128

**Closed as completed by JohnTitor** 2019-12-27 16:33 UTC
